site_name: CIViC NLI

theme:
  name: material
  favicon: images/active-favicon-32x32.png
  logo: images/active-favicon-32x32.png
  features:
    - navigation.top
    # - navigation.sections
    - navigation.instant
    - toc.integrate
repo_url: https://github.com/creisle/civic-nli-ext
repo_name: github
site_dir: build-docs
markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.inlinehilite
  - pymdownx.details
  - pymdownx.superfences
plugins:
  - awesome-pages
nav:
  - index.md
  - tags.md
  - ... | examples/**
  - ...
  - FAQ.md
extra_javascript:
  - https://unpkg.com/ag-grid-community/dist/ag-grid-community.min.js
  - js/table.js
extra_css:
  - custom.css
